plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '2.0.144' apply false
    id 'maven-publish'
}

def stonecutterVersion = System.getProperty('stonecutter.project.version', project.name)
def isNeoForge = stonecutterVersion.contains('neoforge')

if (isNeoForge) {
    apply plugin: 'net.neoforged.moddev'
} else {
    apply plugin: 'net.fabricmc.fabric-loom'
}

stonecutter {
    constants["fabric"] = !isNeoForge
    constants["neoforge"] = isNeoForge
}

group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "Cloth Config"
        url = "https://maven.shedaniel.me/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "NeoForge";
        url = "https://maven.neoforged.net/releases/"
    }
}

if (stonecutterVersion.contains('26.1.2')) {
    project.ext.minecraft_version = '26.1.2'
    project.ext.loader_version = '0.18.5'
    project.ext.fabric_version = '0.155.2+26.1.2'
    project.ext.neoforge_version = '26.1.2.68-beta'
    project.ext.cloth_version = '26.1.154'
} else if (stonecutterVersion.contains('26.1.1')) {
    project.ext.minecraft_version = '26.1.1'
    project.ext.loader_version = '0.18.4'
    project.ext.fabric_version = '0.145.4+26.1.1'
    project.ext.neoforge_version = '26.1.1.5-beta'
    project.ext.cloth_version = '26.1.154'
} else if (stonecutterVersion.contains('26.1')) {
    project.ext.minecraft_version = '26.1'
    project.ext.loader_version = '0.18.4'
    project.ext.fabric_version = '0.145.1+26.1'
    project.ext.neoforge_version = '26.1.0.19-beta'
    project.ext.cloth_version = '26.1.154'
} else {
    project.ext.minecraft_version = '26.2'
    project.ext.loader_version = '0.19.3'
    project.ext.fabric_version = '0.158.0+26.2'
    project.ext.neoforge_version = '26.2.0.59'
    project.ext.cloth_version = '26.2.155'
}

if (isNeoForge) {
    version = "${project.mod_version}-${project.ext.minecraft_version}-neoforge"
} else {
    version = "${project.mod_version}-${project.ext.minecraft_version}-fabric"
}


if (!isNeoForge) {
    loom {
        splitEnvironmentSourceSets()
        mods {
            "imprint" {
                sourceSet sourceSets.main
                sourceSet sourceSets.client
            }
        }
    }
    fabricApi {
        configureDataGeneration { client = true }
    }
} else {
    neoForge {
        version = project.ext.neoforge_version
        runs {
            client {
                client()
            }
        }
    }
}


dependencies {
    if (!isNeoForge) {
        // Fabric-only Dependencies
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        implementation "net.fabricmc:fabric-loader:${project.loader_version}"
        implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
        implementation "me.shedaniel.cloth:cloth-config-fabric:${project.ext.cloth_version}"
        implementation("com.terraformersmc:modmenu:${project.modmenu_version}")
    } else {
    }
}


processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    if (!isNeoForge) {
        filesMatching("fabric.mod.json") {
            expand "version": project.version, "minecraft_version": project.minecraft_version, "loader_version": project.loader_version
        }
    } else {
        filesMatching("META-INF/neoforge.mods.toml") {
            expand "version": project.version, "minecraft_version": project.minecraft_version
        }
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    destinationDirectory = file(rootProject.layout.projectDirectory.dir("versions/all"))
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}