# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
# These will be set dynamically by Stonecutter
# Mod Properties
mod_version=1.1
maven_group=org.tastytrash
archives_base_name=imprint
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.158.0+26.2
modmenu_version=20.0.1

mod_loader=[VERSIONED]

org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot