# The license for your mod. This is mandatory.
license = "MIT" # Change this to your preferred license (e.g., ARR, GPLv3)

# A URL to link to for more information about the mod file
# displayURL = "https://modrinth.com"

[[mods]]
modId = "imprint"

version = "1.0"

# The human-readable name of the mod
displayName = "Imprint"

# A text description of the mod (Keep it short, or wrap with "" for multi-line)
description = "A simple, zero-dependency client-side mod."

# A link to your issue tracker
# issueTrackerURL = "https://github.com"

# Dependency Configuration
# Here we define the platform rules so players don't crash without the basic engine components.
[[dependencies.imprint]]
modId = "neoforge"
type = "required"

versionRange = "[26,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.imprint]]
modId = "minecraft"
type = "required"

versionRange = "[26.1,26.2]"
ordering = "NONE"
side = "CLIENT"